name: dart_console2
version: 3.1.0
homepage: https://github.com/timsneath/dart_console
description: A helper library for command-line applications that need more control over input/output than the standard library provides.
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  ffi: '>=2.0.0 <3.0.0'
  win32: ">=4.1.4 <6.0.0"
  intl: ^0.18.0
  characters: ^1.2.1
dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.4
platforms:
  linux:
  macos:
  windows:
